name = "mb-pack"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]

# For `wrangler pages dev`
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "20"
APP_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "mb-pack-db"
# Fill this after `wrangler d1 create mb-pack-db`
database_id = "REPLACE_WITH_YOUR_D1_ID"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "mb-pack-assets"
preview_bucket_name = "mb-pack-assets-preview"

[site]
bucket = ".vercel/output/static"
